project:
  type: website
  # Register the local extension so its resources and defaults are merged
extensions:
  - _extensions/thermomat/ehu

profile:
  group:
    - [standard, posit, ehu-eu, ehu-es]
  default: ehu-eu

format:
  revealjs:
    theme: [default, styles.scss]
    slide-number: true
    hash: true
    transition: fade
    transition-speed: fast
    background-color: "#ffffff"
    width: 1600
    height: 900
    # Local overrides you keep in /styles (optional)
    css: [styles/styles.scss]
