# _quarto.yml
project:
  type: website
extensions:
  - thermomat/ehu

profile:
  group:
    - [standard, posit, ehu-eu, ehu-es]
  default: posit

format:
  revealjs:
    theme: [default, styles.scss]
    slide-number: true
    hash: true
    transition: fade
    transition-speed: fast
    background-color: "#ffffff"
    width: 1600
    height: 900
    css:
      - _extensions/thermomat/ehu/styles/ehu-fonts-mixed.css
      - _extensions/thermomat/ehu/styles/brand-inline-utilities.css
      - styles/styles.scss
