project:
  type: website
extensions:
  - _extensions/thermomat/ehu
#  - thermomat/ehu

profile:
  group: [[standard, posit, ehu-eu, ehu-es]]
  default: ehu-eu


format:
  revealjs:
    theme: [default, styles.scss]
    slide-number: true
    hash: true
    transition: fade
    transition-speed: fast
    background-color: "#ffffff"
    width: 1600
    height: 900
    incremental: false
    css: [styles/local-overrides.scss]




